### PR TITLE
Remove jcenter refs, fix up tests, another log4j update

### LINKED ISSUE #196: error message about "source not configured" shows {0}
Saw _{0}_ in an error on api.vantiq.com:

> Code: io.vantiq.extsrc.objectRecognition.noQueryConfigured
Message: Source {0} is not configured for Queries. Queries require objRecConfig.general.pollRate < 0

The error text in _ObjectRecognitionCore.java_ needs to remove or escape quotes from the {0} reference.
It looks like several other errors in that file have the same issue.
And also in extjsdk/src/main/java/io/vantiq/extjsdk/_ExtensionWebSocketListener.java_

### LINKED ISSUE #294: Fix up test failures due to ObtainServerConfigs...
wasn't done with a server, so...

### LINKED ISSUE #295: Remove jcenter() references

### PR DESCRIPTION
**Pull request by fhcarter**
Fixes #295
Fixes #294 
Fixes #196

Repairs a few other minor annoyances as well.

Remove obsolete references to jcenter().  Fix a few tests that did not properly set up a config file when using the server.  Repair a variety of obsolete insecam.  These periodically have to be updated when various cameras on the net go offline.  A bit of a whack-a-mole game.

Update log4j to newly release 2.16.0 -- this release disables `jndi` lookups by default -- we don't expect them so no need to do them.

Fixed problem with improperly conditioned test in JMS suite.  Test is now clean with no JMS defined.

Checked dependencies and no one downstream seems to be dragging in older versions of log4j.

### CODE REVIEW

**Comment by fhcarter** [comment]
[Jenkins run](https://jenkins.vantiq.com/jenkins/job/vantiq-extension-sources-branch/41/) -- clean.

Run locally with OpenCV, JDBC, Modbus, etc., extensions defined.  Also clean.

File: jmsSource/src/test/java/io/vantiq/extsrc/jmsSource/TestJMS.java [hunk 1]
```diff
@@ -436,6 +436,8 @@ public void testOddballJMSMessageTypes() {
     
     @Test
     public void testIncorrectOddballJMSTypes() {
+        checkAllJMSProperties(false);
+
```
Comment (fhcarter) [inline jmsSource/src/test/java/io/vantiq/extsrc/jmsSource/TestJMS.java:440]: With this missing, test attempted to use things no defined.  This allows the test to run clean when no properly defined (test is simply skipped -- this is by design).

File: jmsSource/src/test/java/io/vantiq/extsrc/jmsSource/TestJMSBase.java [hunk 2]
```diff
@@ -37,5 +42,16 @@ public static void getProps() {
         testAuthToken = System.getProperty("TestAuthToken", null);
         testVantiqServer = System.getProperty("TestVantiqServer", null);
         testSourceName = System.getProperty("EntConTestSourceName", "testSourceName");
+
+        // Also, set up the config file we'll (not really) use
+        // Make initial Utils.obtainServerConfig() call so that we don't get errors later on
```
Comment (fhcarter) [inline jmsSource/src/test/java/io/vantiq/extsrc/jmsSource/TestJMSBase.java:47]: define config file to keep utilities happy.

File: objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/imageRetriever/TestNetworkStreamRetriever.java [hunk 3]
```diff
@@ -19,8 +19,8 @@
     NetworkStreamRetriever retriever;
     NoSendORCore source;
     
-    final String IP_CAMERA_URL = "http://153.142.207.158:80/-wvhttp-01-/GetOneShot?image_size=640x480&frame_count=1000000000";
-
```
Comment (fhcarter) [inline objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/imageRetriever/TestNetworkStreamRetriever.java:23]: Whack-a-mole with [insecam](https://insecam.org) cameras

File: objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueries.java [hunk 4]
```diff
@@ -769,9 +766,7 @@ public void testInvalidPreCroppingQuery() throws IOException {
         
         File resizedImageFile = new File(OUTPUT_DIR + "/" + outputDirFiles[0].getName());
         BufferedImage resizedImage = ImageIO.read(resizedImageFile);
-        
-        assert resizedImage.getWidth() == IP_CAMERA_WIDTH;
-        assert resizedImage.getHeight() == IP_CAMERA_HEIGHT;
```
Comment (fhcarter) [inline objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueries.java:774]: Unnecessary and adds complexity to aforementioned whack-a-mole game

File: objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/imageRetriever/TestNetworkStreamRetriever.java [hunk 5]
```diff
@@ -19,8 +19,8 @@
     NetworkStreamRetriever retriever;
     NoSendORCore source;
     
-    final String IP_CAMERA_URL = "http://153.142.207.158:80/-wvhttp-01-/GetOneShot?image_size=640x480&frame_count=1000000000";
-    
+    static final String IP_CAMERA_URL = "http://60.45.181.202:8080/mjpg/quad/video.mjpg";
```
Comment (AlexBlumer) [inline objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/imageRetriever/TestNetworkStreamRetriever.java:22]: Why is this one different from `http://49.229.157.154:8080/mjpg/video.mjpg` used in all the later tests?

File: objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueriesLocationMapper.java [hunk 6]
```diff
@@ -45,7 +45,7 @@
     static final String PB_FILE = "coco-" + COCO_MODEL_VERSION + ".pb";
     static final String META_FILE = "coco-" + COCO_MODEL_VERSION + ".meta";
     static final String OUTPUT_DIR = System.getProperty("buildDir") + "/resources/out";
-    static final String IP_CAMERA_ADDRESS = "http://207.192.232.2:8000/mjpg/video.mjpg";
+    static final String IP_CAMERA_ADDRESS = "http://61.208.190.221:8001/cgi-bin/camera?resolution=640&quality=1&Language=0&1639432689";
```
Comment (AlexBlumer) [inline objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueriesLocationMapper.java:48]: Same as above. Could you also have a central file that holds this value, so it only needs to be changed once when a camera is fixed?

**Review by AlexBlumer — APPROVED** [review]
LGTM, just a question about the IPs used for the network cameras

File: objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/imageRetriever/TestNetworkStreamRetriever.java (hunk 5 above)
Comment (fhcarter) [reply objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/imageRetriever/TestNetworkStreamRetriever.java:22]: No particularly good reason except that that's what was found at the time whatever the camera was started to fail.

File: objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueriesLocationMapper.java (hunk 6 above)
Comment (fhcarter) [reply objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueriesLocationMapper.java:48]: I'll add an issue and add a properties file or something with the camera to use.  There are some places where we either don't want or don't care about detecting things but others where we do.  So there are some reasons to have a couple of them.

Comment (fhcarter) [reply objectRecognitionSource/src/test/java/io/vantiq/extsrc/objectRecognition/neuralNet/TestYoloQueriesLocationMapper.java:48]: This is now issue #298
